# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 123456


# Mybatis-Plus Config
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
